export interface Publication {
  year: number;
  slug: string;
  authors: string;
  title: string;
  journal: string;
  volume: string;
  pages: string;
  doi: string;
  pdfFile: string;
}

export const publications: Publication[] = [
  {
    year: 2025,
    slug: "chauvette-2025-auditory-vibrotactile-interactions",
    authors: "Chauvette, L., Grenier, A.S., Albouy, P., Coffey, E., Zatorre, R., & Sharp, A.",
    title: "Auditory and vibrotactile interactions in perception of timbre acoustic features.",
    journal: "Scientific reports",
    volume: "15(1)",
    pages: "38055",
    doi: "10.1038/s41598-025-21908-4",
    pdfFile: "Chauvette_2025_Auditory_Vibrotactile_Interactions.pdf",
  },
  {
    year: 2025,
    slug: "hotton-2025-investigating-implementation-protocol",
    authors: "Hotton, M., Chauvette, L., Poulin, S., & Gagné, J. P.",
    title: "Investigating the implementation of a new protocol and clinical tool designed to assess the audiological needs of individuals with hearing loss in primary care settings.",
    journal: "Frontiers in Audiology and Otology",
    volume: "2",
    pages: "1520014",
    doi: "10.3389/fauot.2024.1520014",
    pdfFile: "Hotton_2025_Inestigating_Implementation_New_Protocol.pdf",
  },
  {
    year: 2025,
    slug: "chauvette-2025-musicianship-octave-illusion",
    authors: "Chauvette, L., Whittom, A., Fecteau, A., Larouche-Gagnon, G., & Sharp, A.",
    title: "Musicianship Modulates Octave Illusion Perception Differently Across Stimulation Frequencies.",
    journal: "Psychological Research",
    volume: "88(78)",
    pages: "1-13",
    doi: "10.1007/s00426-025-02112-5",
    pdfFile: "Chauvette_2025_Musicianship_Modulates_Octave_Illusion.pdf",
  },
  {
    year: 2024,
    slug: "chauvette-2024-multichannel-vibrotactile-glove",
    authors: "Chauvette, L., Leprohon, É., Perron-Houle, L.-P., Pintat, V., Delnavaz, A., Voix, J. & Sharp, A.",
    title: "Multichannel Vibrotactile Glove: Validation of a new device designed to sense vibrations.",
    journal: "IEEE transactions on haptics",
    volume: "17(4)",
    pages: "913-923",
    doi: "10.1109/TOH.2024.3475740",
    pdfFile: "Chauvette_2024_Multichannel_Vibrotactile_Glove.pdf",
  },
  {
    year: 2024,
    slug: "whittom-2024-music-perception-hearing-loss",
    authors: "Whittom, A., Chauvette, L., Bégin, A., Blanchette, I., Tremblay, P., & Sharp, A.",
    title: "Music Perception in Older Adults With Hearing Loss: Protective Effect of Musical Experience.",
    journal: "Ear and hearing",
    volume: "46(3)",
    pages: "707–718",
    doi: "10.1097/AUD.0000000000001615",
    pdfFile: "Whittom_2024_Music_Perception_Older_Adults_Hearing_Loss.pdf",
  },
  {
    year: 2023,
    slug: "chauvette-2023-communication-difficulties-covid",
    authors: "Chauvette, L., Pinsonnault-Skvarenina, A., Sharp, A., Gagné J.-P., Lacerda, A. B. M., & Hotton, M.",
    title: "Perceptions of Adults with Hearing Loss About the Communication Difficulties Generated by the COVID-19 Preventive Measures: A Qualitative Study.",
    journal: "Journal of Speech, Language, and Hearing Research",
    volume: "66(12)",
    pages: "5109–5128",
    doi: "10.1044/2023_JSLHR-23-00163",
    pdfFile: "Chauvette_2023_Perception_Adults_Hearing_Loss.pdf",
  },
  {
    year: 2023,
    slug: "hotton-2023-pilot-evaluation-protocol",
    authors: "Hotton, M., Chauvette, L., & Gagné, J. P.",
    title: "Pilot evaluation of a protocol and a clinical tool developed to assess the audiological needs of adults with hearing loss.",
    journal: "International Journal of Audiology",
    volume: "63(10)",
    pages: "827–835",
    doi: "10.1080/14992027.2023.2211737",
    pdfFile: "Hotton_2023_Pilot_Evaluation_Protocol_Clinical_Tool.pdf",
  },
  {
    year: 2023,
    slug: "whittom-2023-octave-illusion-frequencies",
    authors: "Whittom, A., Couture, F., Chauvette, L., & Sharp, A.",
    title: "Octave illusion: Stimulation frequencies can modulate perception.",
    journal: "Psychological Research",
    volume: "87",
    pages: "2183-2191",
    doi: "10.1007/s00426-023-01805-z",
    pdfFile: "Whittom_2023_Octave_Illusion_Stimulation_Frequency_Modulate_Perception.pdf",
  },
  {
    year: 2022,
    slug: "chauvette-2022-ffr-neural-representation",
    authors: "Chauvette, L., Fournier, P., & Sharp, A.",
    title: "The frequency-following response to assess the neural representation of spectral speech cues in older adults.",
    journal: "Hearing Research",
    volume: "418",
    pages: "108486",
    doi: "10.1016/j.heares.2022.108486",
    pdfFile: "Chauvette_2022_FFR_Assess_Neural_Representation_Spectral.pdf",
  },
  {
    year: 2022,
    slug: "pinsonnault-2022-communication-covid-pandemic",
    authors: "Pinsonnault-Skvarenina, A., Hotton, M., Sharp, A., Chauvette, L., Tremblay, É., Choquette, R., Ansaldo, A. I., Gagné, J. P., & Lacerda, A.",
    title: "Communication during the COVID-19 pandemic: the hearing-impaired perspective.",
    journal: "International journal of audiology",
    volume: "62(12)",
    pages: "1155–1165",
    doi: "10.1080/14992027.2022.2120552",
    pdfFile: "Pinsonnault_2022_Communication_COVID_Hearing_Impaired_Perspective.pdf",
  },
];
